/// Flutter icons IconBmi
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconBmi
///      fonts:
///       - asset: fonts/IconBmi.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconBmi {
  IconBmi._();

  static const _kFontFam = 'IconBmi';

  static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
}
